--CREACION DE TABLA
CREATE TABLE CLIENTE(
CLIENTE_ID NUMBER PRIMARY KEY,
NOMBRE NVARCHAR2(20),
FECHA_NAC DATE,
CELULAR NVARCHAR2(10),
CORREO NVARCHAR2(25)
);

--CREACION DE SECUENCIA
CREATE SEQUENCE CLIENTE_SEQ;

--TRIGGER PARA LA GENERACION DE ID'S
CREATE OR REPLACE TRIGGER ON_INSERT_CLIENTE BEFORE
  INSERT ON CLIENTE FOR EACH ROW BEGIN
  SELECT CLIENTE_SEQ.NEXTVAL INTO :new.CLIENTE_ID FROM dual;
END;

--INSERCION MULTIPLE
INSERT ALL
INTO CLIENTE(NOMBRE,FECHA_NAC,CELULAR,CORREO)VALUES('FELIPE','22-04-2008','0987654321','CORREO1@SERVER.COM')
INTO CLIENTE(NOMBRE,FECHA_NAC,CELULAR,CORREO)VALUES('ANA','13-12-2005','0987654321','CORREO2@SERVER.COM')
SELECT * FROM DUAL;

--ACTUALIZACION DE CORREO ELECTRONICO
UPDATE CLIENTE SET CORREO = 'CORREONUEVO@SERVER.COM' WHERE CLIENTE_ID = 3;

--ELIMINACION DEL SEGUNDO REGISTRO
DELETE FROM CLIENTE WHERE CLIENTE_ID = 2;

SELECT * FROM CLIENTE;